import { describe, expect, it } from "vitest";

import * as ledger from "../src/index.js";

describe("@causalledger/ledger schema boundary", () => {
  it("exposes schema, journal arithmetic, isolated storage and read-only balances", () => {
    expect(ledger.ledgerPackageBoundary).toEqual({
      packageName: "@causalledger/ledger",
      status: "ledger-schema-boundary",
      accountSchemaImplemented: true,
      deterministicAccountValidationImplemented: true,
      transactionSchemaImplemented: true,
      deterministicTransactionValidationImplemented: true,
      entrySchemaImplemented: true,
      deterministicEntryValidationImplemented: true,
      deterministicJournalValidationImplemented: true,
      postingImplemented: false,
      balanceQueriesImplemented: true,
      transactionQueriesImplemented: true,
      storageImplemented: true,
      idempotencyImplemented: true,
      reversalsImplemented: true,
      cashClearingConfigurationImplemented: true,
      providerClearingConfigurationImplemented: true,
      customerLiabilityConfigurationImplemented: true,
      feeExpenseConfigurationImplemented: true,
      revenueConfigurationImplemented: true,
      agentWriteAuthority: false,
      financialTruthEstablishedByValidation: false,
    });
    expect(Object.keys(ledger).sort()).toEqual([
      "ACCOUNT_CATEGORIES",
      "ACCOUNT_CONTRACT_VERSION",
      "ACCOUNT_CURRENCIES",
      "ACCOUNT_NORMAL_BALANCES",
      "ACCOUNT_STATUSES",
      "CASH_CLEARING_ACCOUNT_CONTRACT_VERSION",
      "CUSTOMER_LIABILITY_ACCOUNT_CONTRACT_VERSION",
      "FEE_EXPENSE_ACCOUNT_CONTRACT_VERSION",
      "IdempotentLedgerJournalStorageError",
      "LEDGER_ACCOUNT_BALANCE_CONTRACT_VERSION",
      "LEDGER_ENTRY_CONTRACT_VERSION",
      "LEDGER_ENTRY_MAX_MINOR_UNITS",
      "LEDGER_ENTRY_SIDES",
      "LEDGER_IDEMPOTENCY_CONTRACT_VERSION",
      "LEDGER_JOURNAL_CONTRACT_VERSION",
      "LEDGER_REVERSAL_CONTRACT_VERSION",
      "LEDGER_STORAGE_CONTRACT_VERSION",
      "LEDGER_TRANSACTION_CONTRACT_VERSION",
      "LEDGER_TRANSACTION_QUERY_CONTRACT_VERSION",
      "LEDGER_TRANSACTION_STATUSES",
      "LedgerAccountBalanceReadError",
      "LedgerJournalStorageError",
      "LedgerReversalStorageError",
      "LedgerTransactionReadError",
      "PROVIDER_CLEARING_ACCOUNT_CONTRACT_VERSION",
      "REVENUE_ACCOUNT_CONTRACT_VERSION",
      "createIdempotentLedgerJournalStore",
      "createLedgerAccountBalanceReader",
      "createLedgerJournalStore",
      "createLedgerReversalStore",
      "createLedgerTransactionReader",
      "ledgerPackageBoundary",
      "validateAccountCandidate",
      "validateAccountCatalog",
      "validateCashClearingAccountCandidate",
      "validateCashClearingJournalCandidate",
      "validateCustomerLiabilityAccountCandidate",
      "validateCustomerLiabilityJournalCandidate",
      "validateFeeExpenseAccountCandidate",
      "validateFeeExpenseJournalCandidate",
      "validateLedgerAccountBalanceQueryCandidate",
      "validateLedgerEntryCandidate",
      "validateLedgerIdempotencyCandidate",
      "validateLedgerJournalCandidate",
      "validateLedgerReversalCandidate",
      "validateLedgerTransactionCandidate",
      "validateLedgerTransactionQueryCandidate",
      "validateProviderClearingAccountCandidate",
      "validateProviderClearingJournalCandidate",
      "validateRevenueAccountCandidate",
      "validateRevenueJournalCandidate",
    ]);
  });
});
